const MAX_MESSAGES=14;
const MAX_MESSAGE_CHARS=2400;

function json(res,status,body){res.status(status).setHeader("Content-Type","application/json");res.end(JSON.stringify(body));}
function normalize(value){return String(value||"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g," ").replace(/\s+/g," ").trim();}
function safeMessages(messages){return (Array.isArray(messages)?messages:[]).filter(m=>m&&typeof m.content==="string").slice(-MAX_MESSAGES).map(m=>({role:m.role==="user"?"user":"assistant",content:normalize(m.content).slice(0,MAX_MESSAGE_CHARS)}));}
function hasAny(text,terms){return terms.some(term=>text.includes(term));}
const EMERGENCY=[
 ["severe trouble breathing","breathing difficulty"],["can't breathe","breathing difficulty"],["cannot breathe","breathing difficulty"],["chest pain","chest pain"],["severe chest pain","chest pain"],["face droop","stroke warning sign"],["slurred speech","stroke warning sign"],["one sided weakness","stroke warning sign"],["uncontrolled bleeding","uncontrolled bleeding"],["seizure","seizure"],["passed out","loss of consciousness"],["unconscious","loss of consciousness"],["blue lips","possible oxygen/circulation emergency"],["coughing blood","coughing blood"],["vomiting blood","vomiting blood"],["black stool","possible gastrointestinal bleeding"],["severe abdominal pain","severe abdominal pain"],["sudden worst headache","sudden severe headache"],["worst headache of my life","sudden severe headache"],["vision loss","vision loss"],["paralysis","paralysis"],["anaphylaxis","severe allergic reaction"],["severe allergic reaction","severe allergic reaction"],["overdose","overdose"],["poisoning","possible poisoning"],["suicidal","immediate safety concern"],["kill myself","immediate safety concern"]
];
const TOPICS=[
 ["headache","headache"],["migraine","headache"],["head pain","headache"],["fever","fever"],["temperature","fever"],["cough","respiratory"],["sore throat","respiratory"],["runny nose","respiratory"],["congestion","respiratory"],["shortness of breath","respiratory"],["nausea","digestive"],["vomiting","digestive"],["diarrhea","digestive"],["constipation","digestive"],["stomach pain","digestive"],["abdominal pain","digestive"],["rash","skin"],["itch","skin"],["swelling","skin"],["sleep","sleep"],["insomnia","sleep"],["can't sleep","sleep"],["fatigue","fatigue"],["tired","fatigue"],["dizzy","dizziness"],["dizziness","dizziness"],["period","menstrual"],["pregnant","pregnancy"],["pregnancy","pregnancy"],["anxiety","mental"],["panic","mental"],["depressed","mental"],["stress","mental"]
];
function detectEmergency(text){const s=text.toLowerCase(),hits=[];for(const [term,reason] of EMERGENCY)if(s.includes(term))hits.push({term,reason});return hits;}
function detectTopic(text){const s=text.toLowerCase();for(const [term,topic] of TOPICS)if(s.includes(term))return topic;if(hasAny(s,["medication","medicine","drug","tablet","capsule","pill","dose","dosage","side effect"]))return "medication";if(hasAny(s,["blood pressure","bp","pulse","heart rate","oxygen","spo2","blood sugar","glucose"]))return "vitals";if(hasAny(s,["blood test","lab result","urine test","mri","ct scan","x-ray","ultrasound","scan result","test result"]))return "results";if(hasAny(s,["doctor visit","doctor appointment","prepare for","appointment"]))return "care_visit";if(hasAny(s,["diet","nutrition","food","exercise","workout","gym","weight"]))return "wellness";if(hasAny(s,["hello","hi","hey","good morning","good afternoon","good evening"]))return "greeting";return "general";}
function recentUserText(messages){return messages.filter(m=>m.role==="user").slice(-4).map(m=>m.content).join(" ").toLowerCase();}
function isQuestion(text){return /\?|\bwhy\b|\bwhat\b|\bhow\b|\bcan i\b|\bshould i\b|\bis it\b|\bcould\b|\bdoes\b/.test(text.toLowerCase());}
function answerFor(topic,text){
 const s=text.toLowerCase();
 if(topic==="greeting")return {message:"Hi — I’m Nura. I can help you work through symptoms, medications, test results, sleep, wellbeing, prevention, or questions about preparing for care.",questions:["What is happening today?","When did it start?"]};
 if(topic==="headache")return {message:"Headaches have many possible causes, including dehydration, missed meals, poor sleep, stress, eye strain, infections, medication effects, or migraine. The pattern matters more than the word “headache” alone, so I’ll help you narrow down the useful information without assuming a diagnosis.",questions:["When did it start, and is it getting better, worse, or staying the same?","Where is the pain and how severe is it from 0–10?","Is it throbbing, pressure-like, sharp, or something else — and do you have nausea, light sensitivity, fever, weakness, numbness, vision changes, or a stiff neck?"]};
 if(topic==="sleep")return {message:"Sleep problems can be linked to stress, schedule changes, caffeine or other stimulants, illness, pain, medicines, mood, or sleep disorders. Duration and pattern are useful for deciding what to do next.",questions:["How long has this been happening?","Do you struggle to fall asleep, stay asleep, or wake too early?","About how many hours are you sleeping, and what changed around the time this started?"]};
 if(topic==="fever")return {message:"A raised temperature is a symptom rather than a diagnosis. Infection is common, but the surrounding symptoms and duration matter. If possible, use an actual thermometer reading rather than judging fever by touch.",questions:["What is the highest measured temperature and how was it measured?","How long have you had it?","What other symptoms do you have, and can you drink fluids and urinate normally?"]};
 if(topic==="respiratory")return {message:"Cough, congestion and sore throat can occur with viral infections, allergies, irritation and other conditions. Severity, duration and whether breathing is affected are especially important.",questions:["When did the symptoms begin, and are they improving or worsening?","Do you have fever, shortness of breath, chest pain, wheezing, or coughing up blood?","Any known sick contact, allergy trigger, or recent exposure?"]};
 if(topic==="digestive")return {message:"Digestive symptoms can have many causes, from short-lived infections and food-related problems to medication effects and other conditions. I can help organize the pattern and identify warning signs.",questions:["What symptom is strongest — pain, nausea, vomiting, diarrhea, or constipation?","When did it start and where is any pain located?","Can you keep fluids down, and have you noticed blood, black stool, fever, or severe/worsening pain?"]};
 if(topic==="fatigue")return {message:"Fatigue is common but nonspecific. Sleep quality, stress, infections, nutrition, medicines, mood, and several medical conditions can contribute. Timing and associated symptoms help narrow the possibilities.",questions:["How long have you felt unusually tired?","How are you sleeping, and is the fatigue present even after adequate rest?","Any fever, weight change, breathlessness, pain, bleeding, mood change, or new medication?"]};
 if(topic==="dizziness")return {message:"“Dizzy” can mean feeling faint, off-balance, or like the room is spinning. Those patterns have different causes, so describing the sensation is important.",questions:["Does it feel like you might faint, or like the room is spinning?","When does it happen — standing up, moving your head, or even while sitting still?","Any chest pain, severe headache, weakness, numbness, speech/vision changes, hearing symptoms, or actual fainting?"]};
 if(topic==="skin")return {message:"Skin changes are often best understood from appearance, location, timing and associated symptoms. A rash or lump alone does not identify a cause.",questions:["Where is it and when did it start?","Is it itchy, painful, warm, spreading, blistering, or draining?","Did anything change before it appeared — a new product, medicine, food, bite, injury, or illness?"]};
 if(topic==="menstrual"||topic==="pregnancy")return {message:"I can help organize menstrual or pregnancy-related questions without assuming a diagnosis. Timing, bleeding pattern, symptoms and pregnancy possibility are important context.",questions:["What are you experiencing and when did it start?","When was the first day of your last period, if you know it?","Is pregnancy possible, and are you having severe pain, heavy bleeding, fainting, or other rapidly worsening symptoms?"]};
 if(topic==="medication"){if(hasAny(s,["stop","stopping","double","increase","decrease","change my dose","missed dose"]))return {message:"Medication changes depend on the specific drug, dose, indication, timing and other medicines. I should not tell you to change a prescribed dose or stop a prescription based only on chat. I can explain the general considerations and help you prepare a pharmacist or clinician question.",questions:["What is the exact medicine name and strength on the label?","What were you prescribed it for, and what happened with the dose?","Are you having any new or severe symptoms right now?"]};return {message:"I can explain what a medicine is generally used for, common side effects, interactions to ask about, and questions to take to a pharmacist or clinician. I won’t invent a dose or tell you to change a prescription without appropriate context.",questions:["What is the exact medicine name and strength?","What do you want to know — purpose, side effects, interactions, timing, or something you experienced after taking it?","What other medicines or supplements are you taking, if relevant?"]};}
 if(topic==="vitals")return {message:"A health measurement needs context before it can be interpreted. One number is not always enough, and device readings can vary.",questions:["What is the exact reading and unit?","When was it measured, and were you resting beforehand?","Do you have symptoms right now, and have you seen a different reading repeatedly?"]};
 if(topic==="results")return {message:"I can translate a test report into plain language, but a result should be interpreted with the reason for testing, symptoms and the laboratory’s own reference range. I won’t turn one result into a diagnosis.",questions:["What is the exact test name and result?","What reference range is printed on the report?","Why was the test ordered, and are you having symptoms?"]};
 if(topic==="care_visit")return {message:"For a doctor visit, the most useful preparation is a short timeline: what changed, when it started, what makes it better or worse, medicines and supplements, relevant measurements or test results, and the questions you want answered. Nura can turn that into a concise visit summary.",questions:["What is the main reason for the visit?","When did it start and how has it changed?","What medicines, supplements, measurements, tests, or previous treatments are relevant?"]};
 if(topic==="wellness")return {message:"I can help with practical general guidance around food, activity, sleep and healthy routines. The right approach depends on your goal and health constraints, so I’ll avoid presenting generic advice as a medical prescription.",questions:["What is your main goal?","What does your current routine look like?","Any medical condition, medication, injury, pregnancy, or other constraint that should shape the advice?"]};
 if(topic==="mental")return {message:"I’m happy to talk this through without judging you. Stress, anxiety and low mood can affect sleep, concentration, appetite and daily functioning, but persistent or severe symptoms deserve human clinical support. If you feel unsafe or may hurt yourself or someone else, seek immediate help from emergency services or a trusted person nearby.",questions:["What have you been feeling and for how long?","How is it affecting sleep, work, school, relationships, or daily activities?","Do you feel safe right now?"]};
 if(isQuestion(s))return {message:"I can help you reason through that. I’ll separate what is known from what is only possible, avoid treating a symptom as a diagnosis, and focus on what information would change the next step.",questions:["What prompted the question?","When did this start or change, if it relates to a symptom?","What is the main thing you want to know or decide?"]};
 return {message:"I’m following you. Tell me what is happening, when it started, and what has changed. I’ll help organize the situation, look for safety concerns, explain relevant possibilities, and identify sensible next steps.",questions:["When did this start?","What is the main symptom or concern right now?","What has changed recently — medicines, illness, sleep, diet, stress, exposure, or anything else?"]};
}
export default async function handler(req,res){
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
 try{
  const messages=safeMessages((req.body||{}).messages);
  if(!messages.length)return json(res,400,{error:"A conversation is required."});
  const last=messages[messages.length-1];
  if(last.role!=="user")return json(res,400,{error:"The latest conversation message must be from the user."});
  const emergency=detectEmergency(last.content);
  if(emergency.length)return json(res,200,{message:"What you described may need urgent medical attention. Please seek emergency medical care now or contact your local emergency service. Do not wait for this chat to decide whether you need care. If you are with someone you trust, tell them what is happening.",urgent:true,safetySignals:emergency.map(x=>x.term)});
  const topic=detectTopic(last.content+" "+recentUserText(messages));
  const result=answerFor(topic,last.content);
  const message=result.message+(result.questions?.length?"\n\nA few questions that would help me understand this better:\n"+result.questions.map((q,i)=>(i+1)+". "+q).join("\n"):"");
  return json(res,200,{message,urgent:false,topic,followUpCount:result.questions?.length||0});
 }catch(error){
  console.error("Nura health engine error",error);
  return json(res,200,{message:"I’m still here with you. Tell me the main thing you’re experiencing, when it started, and whether it is getting better or worse. If you have severe or rapidly worsening symptoms, seek urgent medical care rather than waiting for a chat response.",urgent:false,topic:"general",followUpCount:3});
 }
}
