const SYSTEM_PROMPT="You are Nura, a cautious AI health-information companion. You are not a doctor and must not diagnose, prescribe, or claim certainty. Help users organize symptoms, ask useful follow-up questions, explain general health information, and identify appropriate next steps. If potentially life-threatening symptoms are described (severe trouble breathing, severe chest pressure/pain, stroke signs, uncontrolled bleeding, seizure, loss of consciousness, severe allergic reaction, immediate danger), clearly recommend emergency medical care now and keep the response brief. Never tell a user to delay urgent care while chatting. Do not provide individualized prescription changes or dosing instructions. Distinguish possibilities from diagnoses. Ask only a few high-value questions at a time. Never request private keys, seed phrases, passwords, or unnecessary identifying information. Health data sent here is processed server-side to generate the response. Keep answers calm and concise.";
function json(res,status,body){res.status(status).setHeader("Content-Type","application/json");res.end(JSON.stringify(body))}
function redact(v){return String(v||"").replace(/(seed phrase|private key|secret phrase)\s*[:=]?\s*[^\n]*/gi,"[redacted]")}
function localFallback(messages){
 const clean=messages.filter(m=>m&&typeof m.content==="string");
 const last=String(clean[clean.length-1]?.content||"").trim(),s=last.toLowerCase();
 const history=clean.slice(-6).map(m=>String(m.content||"")).join(" ").toLowerCase();
  const urgent=/\b(chest pain|severe chest|can't breathe|cannot breathe|difficulty breathing|trouble breathing|stroke|face droop|slurred speech|uncontrolled bleeding|seizure|unconscious|passed out|anaphylaxis|severe allergic|suicid(?:e|al)|overdose|poisoning|blue lips|coughing blood|vomiting blood|black stool|severe abdominal pain|sudden worst headache|worst headache|vision loss|paralysis)\b/i.test(String(messages[messages.length-1]?.content||""));
 if(urgent)return "What you described may need urgent medical attention. Please seek emergency medical care now or contact your local emergency service. If you are in immediate danger, do not wait for a chat response.";
 const has=(...terms)=>terms.some(t=>s.includes(t));
 const recentHeadache=/\b(headache|head pain|migraine|head ache)\b/.test(history);
 const recentSleep=/\b(sleep|insomnia|can't sleep|cannot sleep|sleeping)\b/.test(history);
 if(recentHeadache&&(has("right","left","side","temple","forehead","back of","behind")||has("pain","ache")))return "Got it — you’re describing the headache in a specific area. The location can be useful, but it does not identify the cause by itself. Tell me when it started, how severe it is from 0–10, what the pain feels like (pressure, throbbing, sharp, or burning), and whether you have nausea, vomiting, light sensitivity, vision changes, weakness, numbness, fever, or a stiff neck. If it suddenly became extremely severe or you develop weakness, confusion, fainting, trouble speaking, or vision loss, seek urgent care.";
 if(has("headache","head pain","migraine"))return "A headache can have many causes, including dehydration, poor sleep, stress, skipped meals, eye strain, infections, or migraine. If it is mild and you otherwise feel well, rest, hydrate, and eat if you have not eaten recently. Tell me when it started, where it hurts, how severe it is from 0–10, and whether you have nausea, vomiting, light sensitivity, vision changes, weakness, numbness, fever, or a stiff neck.";
 if(recentSleep&&(has("why","problem","bad","poor","hours","wake","waking")||has("not sleeping","can't sleep","cannot sleep")))return "Poor sleep can have several causes, including stress, schedule changes, caffeine, illness, medications, pain, or sleep disorders. Tell me how long this has been happening, roughly how many hours you sleep, whether you struggle to fall asleep or stay asleep, and whether anything changed around the time it started.";
 if(has("sleep","insomnia"))return "I can help you work through sleep problems. A useful starting point is your sleep schedule, caffeine or stimulant use, stress, medications, pain, and how long the problem has lasted. Tell me what your nights have been like recently.";
 if(has("fever","temperature","hot"))return "Fever can happen with infections and other conditions. What temperature did you measure, how did you measure it, how long has it lasted, and what other symptoms do you have? If you become very unwell, confused, severely dehydrated, or develop breathing difficulty, seek medical care promptly.";
 if(has("cough","cold","flu","sore throat","runny nose","blocked nose","congestion"))return "Respiratory symptoms can come from several causes, including viral infections, allergies, and irritation. Tell me when they started, whether you have fever, shortness of breath, chest pain, or a known exposure, and whether symptoms are improving or worsening.";
 if(has("stomach","abdominal","belly","diarrhea","vomiting","nausea","constipation"))return "Digestive symptoms can have many causes. Tell me which symptom is bothering you most, when it started, how severe it is, whether you can keep fluids down, and whether there is fever, blood, severe pain, or a major change in your bowel movements.";
 if(has("period","periods","menstrual","pregnant","pregnancy","ovulation","cramps"))return "I can help you understand menstrual or pregnancy-related health questions. Tell me what you’re experiencing, when it started, the first day of your last period if relevant, and whether pregnancy is possible. I can explain general possibilities and what signs would warrant medical care.";
 if(has("medicine","medication","drug","tablet","pill","dose","dosage","side effect"))return "I can explain general information about medicines, common uses, and possible side effects, but I should not tell you to change a prescribed dose or stop a medication without a clinician’s guidance. Tell me the medicine name, what you want to know about it, and any symptoms you’re experiencing.";
 if(has("blood pressure","bp","heart rate","pulse","oxygen","spo2","blood sugar","glucose","cholesterol"))return "I can help you understand a health measurement in context. Tell me the exact reading, the unit, when it was measured, whether you were resting, and your age if relevant. A single reading does not always tell the whole story.";
 if(has("test result","lab result","blood test","urine test","scan","mri","ct scan","x-ray","ultrasound"))return "I can help explain a test result in plain language. Please share the test name, the exact result and reference range shown on the report, plus why the test was done if you know. I can explain what it commonly means, but a result needs clinical context before it can be interpreted as a diagnosis.";
 if(has("anxious","anxiety","panic","stressed","stress","depressed","depression","sad","overwhelmed","mental health"))return "I’m here to help you think this through without judging you. Tell me what you’ve been feeling, how long it has been happening, and how much it is affecting sleep, work, school, or daily life. If you feel you may hurt yourself or someone else, seek immediate help from emergency services or a trusted person nearby.";
 if(has("diet","nutrition","food","weight","lose weight","gain weight","exercise","workout","gym"))return "I can help with general nutrition and activity questions. Tell me your goal, what you currently do or eat, and any relevant health constraints or symptoms. I’ll keep the guidance practical and avoid treating general advice as a medical prescription.";
 if(has("skin","rash","itch","acne","swelling","lump","wound","burn"))return "Skin symptoms are often easier to narrow down from appearance and timing. Tell me where it is, when it started, whether it is painful or itchy, whether it is spreading, and what it looks like (for example red, raised, blistered, dry, or scaly). A photo can be useful if your app supports sharing one.";
 if(has("why ","what is ","what does ","meaning","explain","is it normal","should i","can i","could this","does "))return "Yes — I can help you understand that. Tell me a little more about what you’re asking and what prompted the question. I’ll explain the relevant health information in plain language, distinguish possibilities from diagnoses, and point out when professional care is appropriate.";
 if(has("hello","hi","hey","good morning","good afternoon","good evening"))return "Hi — I’m Nura. Tell me what’s on your mind, whether it’s a symptom, medication, test result, sleep, nutrition, mental wellbeing, or a general health question. I’ll help you work through it step by step.";
 return "I can help with a wide range of health questions — symptoms, medications, test results, sleep, nutrition, mental wellbeing, prevention, and general health information. Tell me what you’re experiencing or what you want to understand, and include when it started and anything that changed around the same time if relevant. I’ll ask only the most useful follow-up questions and explain what to do next. I can’t diagnose or replace a clinician, and urgent symptoms should be assessed promptly.";
}
export default async function handler(req,res){
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
 try{
  const body=req.body||{},messages=Array.isArray(body.messages)?body.messages.slice(-12):[];
  if(!messages.length)return json(res,400,{error:"A conversation is required."});
  const urgent=\b(chest pain|severe chest|can't breathe|cannot breathe|difficulty breathing|trouble breathing|stroke|face droop|slurred speech|uncontrolled bleeding|seizure|unconscious|passed out|anaphylaxis|severe allergic|suicid(?:e|al)|overdose|poisoning|blue lips|coughing blood|vomiting blood|black stool|severe abdominal pain|sudden worst headache|worst headache|vision loss|paralysis)\b/i.test(String(messages[messages.length-1]?.content||""));
  return json(res,200,{message:localFallback(messages),urgent});
 }catch(error){console.error("Nura fallback error",error);return json(res,200,{message:"I’m here to help with your health question. Tell me what you’re experiencing, when it started, and what has changed. If you have severe or rapidly worsening symptoms, seek medical care promptly.",urgent:false})}
}
