import React,{useState}from"react";
import { connectWallet, disconnectWallet, getSavedWallet, restoreWallet, shortenAddress } from "./wallet.js";
import { askNura } from "./api.js";
import { getHealthData, addConversation, addMetric, addAppointment, addMedication, toggleMedication, addCheckin, updateHealthData, clearHealthData, exportHealthData } from "./healthStore.js";
import{createRoot}from"react-dom/client";
import{Activity,ArrowRight,Bell,Brain,CalendarDays,ChevronRight,CircleHelp,ClipboardCheck,Droplets,HeartPulse,Home,LockKeyhole,Menu,MessageCircle,Moon,MoreHorizontal,Pill as PillIcon,ShieldCheck,Sparkles,SunMedium,UserRound,Wallet,X}from"lucide-react";
import"./styles.css";

const chain={id:4663};

function App(){
 const[route,setRoute]=useState(window.location.pathname==="/app"?"app":"home");
 const[menuOpen,setMenuOpen]=useState(false),[wallet,setWallet]=useState(()=>getSavedWallet());
 const walletConnected=!!wallet?.address;
 const go=next=>{window.history.pushState({}, "",next==="app"?"/app":"/");setRoute(next);setMenuOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 React.useEffect(()=>{const f=()=>setRoute(window.location.pathname==="/app"?"app":"home");window.addEventListener("popstate",f);restoreWallet().then(setWallet).catch(()=>setWallet(null));if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});return()=>window.removeEventListener("popstate",f)},[]);
 return route==="app"?<NuraApp wallet={wallet} setWallet={setWallet} goHome={()=>go("home")}/>:<Landing menuOpen={menuOpen} setMenuOpen={setMenuOpen} goApp={()=>go("app")}/>;
}

function Brand({compact=false,onClick}){return <button className={"brand "+(compact?"brand-compact":"")} onClick={onClick}><span className="brand-mark"><i/><i/></span><span>NURA</span></button>}
function Pill({children,tone="blue"}){return <span className={"pill pill-"+tone}>{children}</span>}

function Landing({menuOpen,setMenuOpen,goApp}){
 return <div className="site-shell landing">
  <header className="nav"><Brand/><nav className={menuOpen?"nav-links open":"nav-links"}><button className="active">Home</button><button onClick={goApp}>AI Doctor</button><button onClick={goApp}>Health</button><button onClick={goApp}>Care Plan</button><button onClick={goApp}>Health</button><button onClick={goApp}>Library</button><button onClick={goApp}>About</button></nav><div className="nav-actions"><button className="nav-ghost" onClick={goApp}>Sign in</button><button className="button button-primary button-small" onClick={goApp}>Open Nura <ArrowRight size={15}/></button><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={21}/>:<Menu size={21}/>}</button></div></header>
  <main>
   <section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-copy"><Pill><Sparkles size={12}/> AI-powered health companion</Pill><h1><span>AI Health,</span> powered by <em>Nura</em><br/>Understand <strong>your body.</strong></h1><p>Personal health guidance, symptom conversations, care plans, and health tracking — designed for people who live onchain.</p><div className="hero-actions"><button className="button button-primary" onClick={goApp}>Open Nura <ArrowRight size={17}/></button><button className="button button-soft" onClick={goApp}>Meet AI Doctor <ChevronRight size={16}/></button></div><div className="trust-row"><span><ShieldCheck size={15}/> Private by design</span><span><LockKeyhole size={14}/> You control your data</span><span><Wallet size={14}/> Robinhood Chain ready</span></div></div>
    <div className="hero-stage"><div className="float-card stat-card left"><div className="mini-label"><HeartPulse size={13}/> Heart rate</div><strong>72 <small>BPM</small></strong><span className="good">● In your normal range</span></div><div className="float-card stat-card left lower"><div className="mini-label"><Moon size={13}/> Sleep</div><strong>7h 45m</strong><span className="good">● Rested</span></div>
     <div className="phone-hero"><div className="phone-camera"/><div className="phone-topbar"><span>9:41</span><span>●●●</span></div><div className="phone-title"><span>‹</span> AI Doctor <MoreHorizontal size={16}/></div><div className="health-orbit"><div className="orbit-ring ring-a"/><div className="orbit-ring ring-b"/><div className="health-core"><Brain size={34}/></div><span className="organ o1">🫀</span><span className="organ o2">🫁</span><span className="organ o3">🧠</span><span className="organ o4">🩺</span></div><div className="phone-chat"><div className="bubble">Hi, I’m Nura. What’s going on today?</div><div className="quick-row"><span>Headache</span><span>Sleep</span><span>Medication</span></div></div></div>
     <div className="float-card emergency-card"><div className="emergency-icon">↗</div><div><strong>Emergency support</strong><span>Get urgent help when you need it</span></div><ArrowRight size={17}/></div><div className="glow-base"/>
    </div></section>
   <section className="feature-strip"><div><div className="feature-icon"><MessageCircle/></div><span><b>AI Doctor</b><small>Talk through symptoms</small></span></div><div><div className="feature-icon"><Activity/></div><span><b>Health overview</b><small>See your trends at a glance</small></span></div><div><div className="feature-icon"><CalendarDays/></div><span><b>Care plans</b><small>Appointments & medication</small></span></div><div><div className="feature-icon"><Wallet/></div><span><b>Onchain identity</b><small>Portable health permissions</small></span></div></section>
   <section className="section"><div className="section-heading"><Pill tone="lavender"><Sparkles size={12}/> Built for your everyday</Pill><h2>A calmer way to understand your health.</h2><p>Nura turns scattered health moments into one clear, private place to ask questions, track signals, and plan your next step.</p></div><div className="feature-grid"><FeatureCard icon={<Brain/>} title="AI Doctor" text="Have a natural conversation about symptoms and health questions before deciding what to do next."/><FeatureCard icon={<HeartPulse/>} title="Health signals" text="Bring together the basics — heart rate, sleep, hydration, medications and more."/><FeatureCard icon={<ClipboardCheck/>} title="Care plan" text="Keep appointments, medications and follow-ups in one simple, readable timeline."/></div></section>
   <section className="chain-section"><div><Pill tone="dark"><Wallet size={12}/> Onchain-ready</Pill><h2>Your health identity.<br/><span>Under your control.</span></h2><p>Nura is designed for wallet-native experiences on Robinhood Chain. Connect when you want portable permissions and onchain experiences — never because your care depends on it.</p><button className="button button-dark" onClick={goApp}>Explore the Nura app <ArrowRight size={16}/></button></div><div className="chain-card"><div className="chain-top"><span className="chain-dot"/>ROBINHOOD CHAIN<span className="chain-live">LIVE</span></div><div className="wallet-visual"><Wallet size={30}/><span>0x•••• 8A2C</span></div><div className="permission"><ShieldCheck size={17}/><div><b>Health permissions</b><small>Private · user controlled</small></div><ChevronRight size={16}/></div><div className="permission"><LockKeyhole size={17}/><div><b>Encrypted records</b><small>Access can be revoked</small></div><ChevronRight size={16}/></div></div></section>
  </main>
  <footer className="footer"><Brand compact/><span>© 2026 Nura AI. Health information is educational and not a diagnosis.</span><div><button onClick={goApp}>AI Doctor</button><button onClick={goApp}>App</button><button>Privacy</button></div></footer>
 </div>
}
function FeatureCard({icon,title,text}){return <article className="feature-card"><div className="feature-card-icon">{icon}</div><h3>{title}</h3><p>{text}</p><ChevronRight size={17}/></article>}

function NuraApp({wallet,setWallet,goHome}){
 const[active,setActive]=useState("Home"),[notice,setNotice]=useState(""),[walletBusy,setWalletBusy]=useState(false);
 const connected=!!wallet?.address;
 const nav=["Home","AI Doctor","Health","Appointments","Profile"];
 const connect=async()=>{setWalletBusy(true);try{const next=await connectWallet();setWallet(next);setNotice(`Wallet connected · ${shortenAddress(next.address)} · Robinhood Chain`)}catch(error){setNotice(error?.message||"Wallet connection cancelled.");}finally{setWalletBusy(false);setTimeout(()=>setNotice(""),4200)}};
 const disconnect=async()=>{await disconnectWallet();setWallet(null);setNotice("Wallet disconnected.");setTimeout(()=>setNotice(""),2600)};
 return <div className="app-shell">{notice&&<div className="toast"><ShieldCheck size={16}/>{notice}</div>}<aside className="sidebar"><Brand onClick={goHome}/><div className="side-nav">{nav.map(item=><button key={item} className={active===item?"selected":""} onClick={()=>setActive(item)}>{iconFor(item)}<span>{item}</span></button>)}</div><div className="sidebar-bottom"><div className="privacy-box"><LockKeyhole size={16}/><div><b>Private mode</b><small>Your health data stays under your control.</small></div></div><button className="help-button"><CircleHelp size={17}/> Help & safety</button></div></aside>
  <main className="dashboard"><header className="app-topbar"><div className="mobile-brand"><Brand compact onClick={goHome}/></div><div className="crumb"><span>Good afternoon</span><b>Welcome back</b></div><div className="top-actions"><button className="icon-button"><Bell size={18}/><i/></button><button className={"wallet-button "+(connected?"connected":"")} onClick={connected?disconnect:connect} disabled={walletBusy}><Wallet size={16}/><span>{walletBusy?"Connecting…":connected?shortenAddress(wallet.address):"Connect wallet"}</span></button><div className="avatar">N</div></div></header><div className="dashboard-inner">
   {active==="Home"&&<DashboardHome onDoctor={()=>setActive("AI Doctor")}/>}
   {active==="AI Doctor"&&<DoctorPage/>}{active==="Health"&&<HealthPage/>}{active==="Appointments"&&<AppointmentsPage/>}{active==="Profile"&&<ProfilePage wallet={wallet} onConnect={connect} onDisconnect={disconnect} walletBusy={walletBusy}/>}
  </div></main><nav className="mobile-nav">{nav.map(item=><button key={item} className={active===item?"selected":""} onClick={()=>setActive(item)}>{iconFor(item)}<span>{item}</span></button>)}</nav></div>
}
function iconFor(item){const p={size:18,strokeWidth:1.8};if(item==="Home")return <Home {...p}/>;if(item==="AI Doctor")return <Sparkles {...p}/>;if(item==="Health")return <HeartPulse {...p}/>;if(item==="Appointments")return <CalendarDays {...p}/>;return <UserRound {...p}/>}

function DashboardHome({onDoctor}){return <div className="dashboard-page"><section className="welcome-grid"><div className="welcome-card"><div className="welcome-copy"><Pill><Sparkles size={12}/> Your AI health companion</Pill><h1>Understand your health.<br/><span>One conversation at a time.</span></h1><p>Ask Nura about symptoms, medications, sleep, hydration and everyday health questions.</p><button className="button button-primary" onClick={onDoctor}>Talk to Nura <ArrowRight size={16}/></button></div><div className="welcome-art"><div className="art-glow"/><div className="mini-orb"><Brain size={34}/></div><span>●</span><span>●</span><span>●</span></div></div><div className="today-card"><div className="card-head"><span>Today</span><MoreHorizontal size={17}/></div><Today label="Heart rate" value="72 BPM" icon={<HeartPulse/>} tone="blue" status="Normal"/><Today label="Sleep" value="7h 45m" icon={<Moon/>} tone="purple" status="Good"/><Today label="Hydration" value="5 / 8 cups" icon={<Droplets/>} tone="mint" status="62%"/></div></section><TitleRow small="YOUR HEALTH" title="Overview"/><section className="overview-grid"><MetricCard icon={<HeartPulse/>} label="Heart rate" value="72" unit="BPM" note="Resting · within your range" tone="blue"/><MetricCard icon={<Moon/>} label="Sleep" value="7h 45m" note="Goal 7–9 hours" tone="purple"/><MetricCard icon={<Activity/>} label="Activity" value="6,842" unit="steps" note="68% of daily goal" tone="mint"/><MetricCard icon={<Droplets/>} label="Hydration" value="1.4" unit="L" note="Keep sipping through the day" tone="orange"/></section><TitleRow small="NEXT UP" title="Care timeline"/><div className="timeline-card"><TimelineItem icon={<CalendarDays/>} title="Dr. Peterson · General check-up" meta="Tomorrow · 10:30 AM" tag="Confirmed"/><TimelineItem icon={<PillIcon/>} title="Vitamin D · 1 tablet" meta="Today · 8:00 PM" tag="Medication"/><TimelineItem icon={<MessageCircle/>} title="Follow up with Nura" meta="After your appointment" tag="AI note"/></div></div>}
function Today({icon,label,value,tone,status}){return <div className="today-metric"><div className={"metric-icon "+tone}>{icon}</div><div><small>{label}</small><strong>{value}</strong></div><span className="metric-status">{status}</span></div>}
function TitleRow({small,title}){return <section className="section-title-row"><div><small>{small}</small><h2>{title}</h2></div><button className="link-button">View all <ArrowRight size={15}/></button></section>}
function MetricCard({icon,label,value,unit,note,tone}){return <article className="metric-card"><div className={"metric-icon "+tone}>{icon}</div><div className="metric-card-label">{label}<MoreHorizontal size={15}/></div><div className="metric-value">{value} <small>{unit}</small></div><div className="metric-note">{note}</div><div className="sparkline">{[1,2,3,4,5,6,7].map(i=><span key={i}/>)}</div></article>}
function TimelineItem({icon,title,meta,tag}){return <div className="timeline-item"><div className="timeline-icon">{icon}</div><div><b>{title}</b><small>{meta}</small></div><Pill tone="mint">{tag}</Pill><ChevronRight size={16}/></div>}

function DoctorPage(){
 const[messages,setMessages]=useState([{role:"assistant",from:"nura",content:"Hi, I’m Nura. Tell me what’s going on today — symptoms, sleep, medication, or anything you’re unsure about."}]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[urgent,setUrgent]=useState(false);
 const send=async preset=>{const text=(preset??input).trim();if(!text||busy)return;const next=[...messages,{role:"user",from:"user",content:text}];setMessages(next);setInput("");setBusy(true);try{const result=await askNura({messages:next.map(m=>({role:m.role,content:m.content})),healthContext:getHealthData()});const reply={role:"assistant",from:"nura",content:result.message};setMessages([...next,reply]);setUrgent(!!result.urgent);addConversation([...next,reply])}catch(error){setMessages([...next,{role:"assistant",from:"nura",content:error?.message||"Nura could not reach the AI service. Your message remains on this device."}])}finally{setBusy(false)}};
 return <div className="doctor-page"><div className="doctor-main"><div className="page-kicker"><Pill><Sparkles size={11}/> Nura AI Doctor</Pill><span>Educational support · not a diagnosis</span></div><h1>How are you feeling?</h1><p className="page-sub">Describe what’s happening in your own words. Nura can structure the information and help you think through sensible next steps.</p>{urgent&&<div className="urgent-banner"><AlertTriangle size={18}/><div><b>Urgent symptoms detected</b><span>Please seek urgent medical care now. Do not wait for this chat to decide what to do.</span></div></div>}<div className="chat-window">{messages.map((m,i)=><div className={"chat-row "+m.from} key={i}><div className="chat-avatar">{m.from==="nura"?<Sparkles size={15}/>:"N"}</div><div className="chat-bubble">{m.content}</div></div>)}{busy&&<div className="typing">Nura is thinking…</div>}</div><div className="quick-prompts"><button onClick={()=>send("I have a headache")}>Headache</button><button onClick={()=>send("I’m not sleeping well")}>Sleep</button><button onClick={()=>send("I have a question about a medication")}>Medication</button><button onClick={()=>send("I want to understand my symptoms")}>Symptoms</button></div><div className="chat-composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Tell Nura what’s going on…"/><button onClick={()=>send()} disabled={busy}><ArrowRight size={17}/></button></div></div><aside className="doctor-side"><div className="side-panel"><h3>Safety first</h3><p>For severe or rapidly worsening symptoms, seek urgent medical care rather than relying on an AI assistant.</p><button onClick={()=>setUrgent(true)}><AlertTriangle size={15}/> Emergency guidance <ChevronRight/></button></div><div className="side-panel"><h3>What Nura can do</h3><div className="capability"><ShieldCheck size={14}/> Structure symptoms</div><div className="capability"><ShieldCheck size={14}/> Explain general health information</div><div className="capability"><ShieldCheck size={14}/> Help prepare for a clinician visit</div></div></aside></div>
}
function HealthPage(){return <div className="dashboard-page"><div className="page-kicker"><Pill tone="lavender"><Activity size={11}/> Health overview</Pill></div><h1 className="page-title">Your health, at a glance.</h1><p className="page-sub">A simple view of the signals you choose to track.</p><div className="overview-grid health-grid"><MetricCard icon={<HeartPulse/>} label="Heart rate" value="72" unit="BPM" note="Resting · normal" tone="blue"/><MetricCard icon={<Moon/>} label="Sleep" value="7h 45m" note="Last night" tone="purple"/><MetricCard icon={<Droplets/>} label="Hydration" value="1.4" unit="L" note="Today" tone="mint"/><MetricCard icon={<Activity/>} label="Steps" value="6,842" note="Today" tone="orange"/></div><div className="health-lower"><div className="wide-card"><div className="card-head"><div><small>WEEKLY TREND</small><h3>Resting heart rate</h3></div><Pill>72 BPM</Pill></div><div className="fake-chart"><div className="chart-line"/>{[1,2,3,4,5,6,7].map(i=><span key={i}>{i===7?"Today":""}</span>)}</div></div><div className="wide-card"><div className="card-head"><div><small>CHECK-IN</small><h3>How are you today?</h3></div><SunMedium size={18}/></div><div className="mood-row">{["😔","😐","🙂","😊"].map((x,i)=><button key={x} className={i===2?"selected":""}>{x}<span>{["Low","Okay","Good","Great"][i]}</span></button>)}</div></div></div></div>}
function AppointmentsPage(){return <div className="dashboard-page"><div className="page-kicker"><Pill tone="mint"><CalendarDays size={11}/> Care plan</Pill></div><h1 className="page-title">Appointments & care.</h1><p className="page-sub">Keep your next steps visible without the clutter.</p><div className="appointment-banner"><div className="doctor-avatar">EP</div><div><Pill tone="mint">Confirmed</Pill><h3>Dr. Emily Peterson</h3><p>General Physician · Tomorrow at 10:30 AM</p></div><button className="button button-soft">View details <ChevronRight size={15}/></button></div><div className="wide-card"><div className="card-head"><div><small>MEDICATIONS</small><h3>Today</h3></div><button className="link-button">Manage <ArrowRight size={14}/></button></div><div className="med-row"><div className="med-icon"><PillIcon/></div><div><b>Vitamin D</b><small>1 tablet · with food</small></div><span>8:00 PM</span><Pill tone="mint">Upcoming</Pill></div><div className="med-row"><div className="med-icon"><PillIcon/></div><div><b>Magnesium</b><small>1 capsule · evening</small></div><span>9:00 PM</span><Pill tone="blue">Scheduled</Pill></div></div></div>}
function ProfilePage({wallet,onConnect,onDisconnect,walletBusy}){
 const connected=!!wallet?.address;return <div className="dashboard-page"><div className="profile-head"><div className="profile-avatar">N</div><div><div className="page-kicker"><Pill tone="lavender"><UserRound size={11}/> Profile</Pill></div><h1 className="page-title">Your Nura profile</h1><p className="page-sub">Manage your preferences and onchain permissions.</p></div></div><div className="profile-grid"><div className="wide-card"><div className="card-head"><div><small>WALLET</small><h3>Robinhood Chain</h3></div><Wallet size={19}/></div><div className="wallet-profile">{connected?<><div><b>Connected</b><small>{shortenAddress(wallet.address)} · Robinhood Chain · {wallet.connector||"Wallet"}</small></div><div className="wallet-profile-actions"><Pill tone="mint">Active</Pill><button className="button button-soft button-small" onClick={onDisconnect}>Disconnect</button></div></>:<><div><b>Not connected</b><small>Use a browser wallet or WalletConnect on mobile and desktop.</small></div><button className="button button-primary button-small" onClick={onConnect} disabled={walletBusy}>{walletBusy?"Connecting…":"Connect"}</button></>}</div></div><div className="wide-card"><div className="card-head"><div><small>PRIVACY</small><h3>Health permissions</h3></div><LockKeyhole size={19}/></div><div className="toggle-row"><div><b>Private health mode</b><small>Keep health conversations separate from wallet activity.</small></div><div className="fake-toggle on"><span/></div></div><div className="toggle-row"><div><b>Share anonymized insights</b><small>Off by default.</small></div><div className="fake-toggle"><span/></div></div></div></div></div>}

createRoot(document.getElementById("root")).render(<App/>);
